version: '3.8'

services:
  db:
    container_name: cloud_store-archakov-course--database
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    networks:
      - cloud_storage
  server:
    container_name: cloud_store-archakov-course--server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/uploads:/usr/src/app/uploads
      - ./server/src:/usr/src/app/src
      - /usr/src/app/node_modules
    ports:
      - ${API_PORT}:3001
    depends_on:
      - db
    networks:
      - cloud_storage
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=db
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped
networks:
  cloud_storage: